name: social_media
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  image_cropper: ^9.1.0

  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
